version: '3'

services:
  server:
    build: ./server
    env_file: ./.env
    expose:
      - 5000
    environment:
      API_HOST: http://localhost:3000
      API_SERVER_PORT: 5000
    ports:
      - '5000:5000'
    volumes:
      - ./server/src:/src/app/server/src
    command: npm run start

  client:
    build: ./client
    environment:
      - 'API_APP_PORT=3000'
    expose:
      - 3000
    ports:
      - '3000:3000'
    volumes:
      - ./client/src:/src/app/client/src
      - ./client/public:/src/app/client/public
    links:
      - server
    command: npm run start
